package io.jenkins.plugins.smart_retry.model;

public enum FailureType {
    AGENT_LOST,
    SCM_TRANSIENT,
    NETWORK_TRANSIENT,
    ARTIFACT_REPO_TRANSIENT,
    IDENTITY_PROVIDER_TRANSIENT,
    SCM_CONFIGURATION_FAILURE,
    USER_ABORT,
    PIPELINE_LOGIC_FAILURE,
    COMPILATION_FAILURE,
    TEST_ASSERTION_FAILURE,
    DEPLOYMENT_FAILURE,
    UNKNOWN
}
